name: Codio
description: Codio, a application made to teach coding to people.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.6.0
  yaml: ^2.2.1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_spinkit: "^4.1.2"
  package_info: "0.4.1"
  google_fonts: ^1.1.0

flutter:
  assets:
    - assets/icons/
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/CodioIconBlack.png"
