name: Codio
description: Codio, a application made to teach coding to people.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.6.0
  google_fonts: ^1.1.0
  provider: null
  shared_preferences: ^0.5.8
  flutter_spinkit: "^4.1.2"
  flutter_native_splash: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter:
  assets:
    - assets/icons/
    - assets/fonts/
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/CodioIconBlack.png"

flutter_native_splash:
  image: assets/icons/splash.png
  color: "22241e"
  android_disable_fullscreen: true
  ios: false
